remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Advanced 2D and 3D Imaging for Mobile System
description:
When: December 17, 2025
Where: ICVGIP, IIT Mandi
